import gradio as gr
from dailymed import get_drug_leaflet
from personalise import personalise, generate_personal_summary
from schema import UserProfile


def run_legimed(drug_name, age_group, pregnant, kidney_issue,
                liver_issue, other_meds, model, tokenizer):
    """Main pipeline function called by Gradio."""
    from extract import extract_drug_info_robust

    try:
        # Validate input
        if not drug_name.strip():
            return "⚠️ Please enter a drug name first."

        # Step 1: Fetch leaflet from DailyMed
        leaflet_text = get_drug_leaflet(drug_name.strip())
        if not leaflet_text:
            return f"❌ '{drug_name}' not found in DailyMed. Please check the spelling and try again."

        # Step 2: Extract structured info with Gemma 4
        drug_info = extract_drug_info_robust(leaflet_text, model, tokenizer)

        # Step 3: Build user profile
        other_meds_list = [m.strip() for m in other_meds.split(",") if m.strip()]
        profile = UserProfile(
            age_group=age_group,
            pregnant=pregnant,
            kidney_issue=kidney_issue,
            liver_issue=liver_issue,
            other_medications=other_meds_list
        )

        # Step 4: Personalise warning order
        drug_info = personalise(drug_info, profile)

        # Step 5: Generate AI personalised summary
        personal_summary = generate_personal_summary(
            drug_info, profile, model, tokenizer
        )

        # Step 6: Format output
        output = f"# {drug_info.drug_name}\n"
        output += f"**Drug class:** {drug_info.drug_class}  \n"
        output += f"**Active ingredient:** {drug_info.active_ingredient}\n\n"
        output += "---\n\n"

        # AI personalised summary — the key differentiator
        output += "## 🤖 Your personal summary\n"
        output += f"> {personal_summary}\n\n"
        output += "---\n\n"

        # When to take
        output += "## When to take\n"
        for d in drug_info.dosage_instructions:
            food = "with food" if d.with_food else "without food"
            output += f"- **{d.time_of_day.capitalize()}**: {d.amount} — {food}\n"
            if d.notes:
                output += f"  _{d.notes}_\n"

        # Side effects
        output += "\n---\n\n## Side effects\n"
        severity_label = {
            "HIGH": "🔴 Seek emergency help",
            "MEDIUM": "🟡 Call your doctor",
            "LOW": "🟢 Monitor"
        }
        for se in drug_info.side_effects:
            label = severity_label.get(se.severity, "🟢 Monitor")
            output += f"- {label} — **{se.name}**: {se.description}\n"

        # Food & drink
        output += "\n---\n\n## Food & drink\n"
        action_label = {
            "avoid": "🚫 Avoid",
            "caution": "⚠️ Caution",
            "ok": "✅ OK"
        }
        for fi in drug_info.food_interactions:
            label = action_label.get(fi.action, "⚠️ Caution")
            output += f"- {label} — **{fi.substance}**: {fi.reason}\n"

        # Personalised warnings
        if drug_info.warnings:
            output += "\n---\n\n## Warnings\n"
            for w in drug_info.warnings:
                output += f"- ⚠️ {w.text}\n"

        # Emergency
        if drug_info.emergency_signs:
            output += "\n---\n\n## 🚨 Emergency — seek help immediately if:\n"
            for e in drug_info.emergency_signs:
                output += f"- {e}\n"

        # Contraindications
        if drug_info.contraindications:
            output += "\n---\n\n## Do not take if you have:\n"
            for c in drug_info.contraindications:
                output += f"- {c}\n"

        output += "\n---\n_Generated by Legimed · Powered by Gemma 4 · For reference only · Always consult your doctor._"
        return output

    except Exception as e:
        return f"Something went wrong: {str(e)}\n\nPlease try again or check the drug name."


def build_demo(model, tokenizer):
    """Build and return Gradio demo with model injected."""

    def _run(drug_name, age_group, pregnant, kidney_issue, liver_issue, other_meds):
        return run_legimed(drug_name, age_group, pregnant, kidney_issue,
                           liver_issue, other_meds, model, tokenizer)

    with gr.Blocks(title="Legimed", theme=gr.themes.Soft()) as demo:
        gr.Markdown("""
        # Legimed — Your Medication, Made Legible
        *Turn any medication name into a personalized guide · Powered by Gemma 4 · Offline · Free*
        """)

        with gr.Row():
            with gr.Column(scale=1):
                gr.Markdown("### Drug")
                drug_input = gr.Textbox(
                    label="Drug name",
                    placeholder="e.g. warfarin, metformin, amlodipine",
                    value="warfarin"
                )

                gr.Markdown("### Your profile")
                age_group = gr.Radio(
                    choices=["adult", "elderly"],
                    value="adult",
                    label="Age group"
                )
                pregnant = gr.Checkbox(label="Pregnant or breastfeeding")
                kidney_issue = gr.Checkbox(label="Kidney condition")
                liver_issue = gr.Checkbox(label="Liver condition")
                other_meds = gr.Textbox(
                    label="Other medications (comma separated)",
                    placeholder="e.g. metformin, atorvastatin"
                )
                submit_btn = gr.Button(
                    "Generate my guide",
                    variant="primary",
                    size="lg"
                )

            with gr.Column(scale=2):
                gr.Markdown("### Your personalized guide")
                output = gr.Markdown(
                    value="_Enter a drug name and fill in your profile, then click **Generate my guide**._"
                )

        submit_btn.click(
            fn=lambda: "⏳ Generating your personalized guide... This takes about 45 seconds. Please wait.",
            inputs=None,
            outputs=output,
            queue=False
        ).then(
            fn=_run,
            inputs=[drug_input, age_group, pregnant,
                    kidney_issue, liver_issue, other_meds],
            outputs=output
        )

        gr.Markdown("""
        ---
        *Legimed · Gemma 4 Good Hackathon 2026 · Apache 2.0 · [GitHub](https://github.com/LorraineWong/legimed)*
        """)

    return demo
